### ISSUE TITLE
Does not work with TLS?

### ISSUE THREAD

**Issue by EugenMayer** [larsks/novaconsole#3]
Thank you for this little helper.
 
 Am i right now assume that it is not working with a `wss://` based URL?

When trying it using 

```
nova get-serial-console <server>
novaconsole --url <URL>
```

It connects, but when i press enter, it just disconnects right away

```
WARNING:novaconsole.client:connected to: wss://<FQDN>:6083/?token=<TOKEN>
WARNING:novaconsole.client:type "~." to disconnect
```
pressing enter leads to 

```
ERROR:novaconsole:remote host closed connection: Connection to remote host was lost
```

Any ideas, what it might be caused by? The certificate is an official one, normal novnc terminals work with the encrypted channel.

**Comment by larsks** [comment]
> Am i right now assume that it is not working with a wss:// based URL?

I think that's probably correct: when this code was written (7 years ago!) I don't know if that was a supported option on the server side. If you'd like to contribute the necessary changes I'd be happy to merge them.

**Comment by EugenMayer** [comment]
I would love to contribute, but really not keen with those sockets neither the protocol in this case. Do you have a pointer where to start looking? I would try to dig deeper surely. Thanks!

**Comment by EugenMayer** [comment]
Well it seems current forks already fix this https://github.com/jmceleney/novaconsole/commit/f866350ad39599fe7baf6acc134439b9124c8924

https://github.com/jmceleney/novaconsole also did some more fixes to support nova-serialproxy ( https://github.com/jmceleney/novaconsole/commit/0763cc5a6b9ee10a2249749a437df729b3a925c9) - which i do most probably also use in a kolla tls setup. 

You are no longer maintaining this one here, right?
